import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/footer";
import Decoration from "@/components/styling/Decoration";
import { AccountMenu } from "@/components/account-menu";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en" className="scroll-smooth motion-reduce:scroll-auto">
        <body className="bg-gray-950 text-gray-100 antialiased motion-reduce:transform-none">
          <main className="min-h-screen relative overflow-hidden">
            <Decoration />
            <AccountMenu />
            <div className="container mx-auto px-4 md:px-6 py-8 relative z-10">
              {children}
            </div>
            <Toaster />
            <Footer />
          </main>
        </body>
      </html>
    </ClerkProvider>

  );
}